import type { App, ChampionTaskItem } from '../types'

export const CHAMPION_TASKS: ChampionTaskItem[] = [
  {
    id: 'ct1',
    appId: 'docusign',
    appName: 'DocuSign',
    taskType: 'onboarding',
    userName: 'Emma Garcia',
    userEmail: 'emma.garcia@company.com',
    userJobTitle: 'Graphic Designer',
    userDepartment: 'Design',
    dueDate: 'Jan 29, 2026',
    steps: [
      { id: 's1', title: 'Added user with email: emma.garcia@company.com', completed: true },
      { id: 's2', title: 'Assigned correct permission level: Sender', completed: false },
      { id: 's3', title: 'Added to group: Sales Team', completed: false },
      { id: 's4', title: 'Confirmed user received activation email and can log in', completed: false },
    ],
    instructions: [
      { id: 'i1', title: 'Access DocuSign Admin', subSteps: ['Go to admin.docusign.com', 'Sign in with your admin account'] },
      { id: 'i2', title: 'Navigate to User Management', subSteps: ['Click "Users" in the left navigation menu', 'Click "Add Users" button in the top right'] },
      { id: 'i3', title: 'Add the New User', subSteps: ["Enter the user's work email address", 'Enter their first and last name', 'Select permission level: Sender', 'Click "Add User"'] },
      { id: 'i4', title: 'Assign to Group', subSteps: ['Click on the user\'s name', 'Click the "Groups" tab', 'Click "Add to Groups"', 'Select "Sales Team"', 'Click "Save"'] },
      { id: 'i5', title: 'Verify User Access', subSteps: ['User will receive an activation email', 'Ask them to check inbox (including spam)', 'Have them click "Activate Account"', 'Confirm they can log in successfully'] },
    ],
    commonIssues: [
      { question: 'Activation email not received?', answer: 'Check spam folder or resend from user profile' },
      { question: 'Login issues?', answer: 'Reset your password or contact support' },
      { question: 'Need to update account information?', answer: 'Access settings in your profile to make changes' },
    ],
  },
  {
    id: 'ct2',
    appId: 'ms-teams',
    appName: 'MS Teams',
    taskType: 'onboarding',
    userName: 'Emma Garcia',
    userEmail: 'emma.garcia@company.com',
    userJobTitle: 'Graphic Designer',
    userDepartment: 'Design',
    dueDate: 'Jan 30, 2026',
    steps: [
      { id: 's1', title: 'Added user to Microsoft 365', completed: false },
      { id: 's2', title: 'Added to relevant Teams channels', completed: false },
      { id: 's3', title: 'Configured notification settings', completed: false },
      { id: 's4', title: 'Verified login and confirmed access', completed: false },
    ],
    instructions: [
      { id: 'i1', title: 'Access Microsoft 365 Admin Center', subSteps: ['Go to admin.microsoft.com', 'Sign in with your admin account'] },
      { id: 'i2', title: 'Add the User', subSteps: ['Navigate to Users → Active Users → Add a user', 'Fill in name and username', 'Assign a Microsoft 365 Business license that includes Teams'] },
      { id: 'i3', title: 'Add to Teams Channels', subSteps: ['Open Microsoft Teams', 'Go to each team the user should join', 'Click the three-dot menu → "Add member"', 'Search for the user by email'] },
      { id: 'i4', title: 'Configure Notifications', subSteps: ['Enable Activity and Mentions notifications', 'For high-volume channels, set to "Only @mentions"'] },
    ],
    commonIssues: [
      { question: 'User cannot find Teams in their apps?', answer: 'Verify their Microsoft 365 license includes Teams' },
      { question: 'Channels not visible?', answer: 'Ensure the user was added to the correct team, not just a channel' },
    ],
  },
  {
    id: 'ct3',
    appId: 'figma',
    appName: 'Figma',
    taskType: 'onboarding',
    userName: 'Emma Garcia',
    userEmail: 'emma.garcia@company.com',
    userJobTitle: 'Graphic Designer',
    userDepartment: 'Design',
    dueDate: 'Jan 30, 2026',
    steps: [
      { id: 's1', title: 'Invited user to Figma organization', completed: true },
      { id: 's2', title: 'Added to design team and projects', completed: true },
      { id: 's3', title: 'Shared onboarding resources', completed: false },
      { id: 's4', title: 'Confirmed access', completed: false },
    ],
    instructions: [
      { id: 'i1', title: 'Invite to Organization', subSteps: ['Go to Organization settings', 'Under Members, click "Invite members"', "Enter the user's email and select Editor or Viewer role"] },
      { id: 'i2', title: 'Add to Teams and Projects', subSteps: ['Navigate to the relevant Team', 'Click "Invite" and add the user', 'Set project permissions to Edit or View as needed'] },
      { id: 'i3', title: 'Share Onboarding Resources', subSteps: ['Send link to internal design system file', 'Share link to team onboarding document', 'Recommend Figma basics tutorial at help.figma.com'] },
    ],
    commonIssues: [
      { question: 'Invitation email not received?', answer: 'Check spam folder or resend from Organization settings' },
      { question: 'User has view-only access?', answer: 'Update their permission to Editor in the project settings' },
    ],
  },
  {
    id: 'ct4',
    appId: 'asana',
    appName: 'Asana',
    taskType: 'onboarding',
    userName: 'Guy Hawkins',
    userEmail: 'guy.hawkins@company.com',
    userJobTitle: 'Project Manager',
    userDepartment: 'Operations',
    dueDate: 'Jan 28, 2026',
    steps: [
      { id: 's1', title: 'Invited user to Asana workspace', completed: false },
      { id: 's2', title: 'Added to relevant projects and teams', completed: false },
      { id: 's3', title: 'Assigned onboarding tasks', completed: false },
      { id: 's4', title: 'Confirmed access', completed: false },
    ],
    instructions: [
      { id: 'i1', title: 'Access Admin Console', subSteps: ['Go to your Asana workspace', 'Click workspace name → Admin Console'] },
      { id: 'i2', title: 'Invite the User', subSteps: ['Under Members, select "Invite people"', "Enter the user's email and choose their role", 'Send the invitation'] },
      { id: 'i3', title: 'Add to Projects', subSteps: ['Open each project the user needs access to', 'Click the Members icon and add the user', 'Repeat for all relevant team workspaces'] },
      { id: 'i4', title: 'Assign Onboarding Tasks', subSteps: ['Use onboarding project template', 'Assign tasks: review active projects, set up dashboard, read team process doc'] },
    ],
    commonIssues: [
      { question: 'User cannot see a project?', answer: 'Verify they were added as a member in the project settings' },
      { question: 'Invitation expired?', answer: 'Resend from Admin Console → Members' },
    ],
  },
  {
    id: 'ct5',
    appId: 'miro',
    appName: 'Miro',
    taskType: 'onboarding',
    userName: 'Brooklyn Simmons',
    userEmail: 'brooklyn.simmons@company.com',
    userJobTitle: 'UX Designer',
    userDepartment: 'Design',
    dueDate: 'Jan 28, 2026',
    steps: [
      { id: 's1', title: 'Invited user to Miro team', completed: false },
      { id: 's2', title: 'Shared relevant boards', completed: false },
      { id: 's3', title: 'Introduced Miro basics', completed: false },
      { id: 's4', title: 'Confirmed access', completed: false },
    ],
    instructions: [
      { id: 'i1', title: 'Invite to Miro Team', subSteps: ['Go to your Miro dashboard', 'Click on your team name → "Invite team members"', "Enter the user's work email and set role to Member"] },
      { id: 'i2', title: 'Share Boards', subSteps: ['Open each board the user needs access to', 'Click "Share" in the top right', 'Add user by email and set access to Editor or Commenter'] },
      { id: 'i3', title: 'Share Onboarding Resources', subSteps: ['Share the Miro Quick Start guide (help.miro.com)', 'Share internal template board if available'] },
      { id: 'i4', title: 'Verify Access', subSteps: ['Ask the user to sign in to Miro and open a shared board', 'Confirm they can interact with the content'] },
    ],
    commonIssues: [
      { question: 'Board not visible after joining?', answer: 'Ask the user to refresh or check the "Shared with me" section' },
      { question: 'Cannot edit board?', answer: 'Update their access level from Commenter to Editor in board share settings' },
    ],
  },
]

export const APPS: App[] = [
  {
    id: 'trello',
    name: 'Trello',
    description: 'Visual project management with boards and cards',
    categories: ['Project Management', 'Collaboration'],
    vendor: 'Microsoft Corporation',
    logoColor: '#0052CC',
    logoInitials: 'TR',
    status: 'active',
    primaryChampion: 'Jane Cooper',
    userCount: 35,
    lastSync: '5 minutes ago',
    provisioning: 'champion',
    appliesTo: [
      { id: '1', name: 'Riverstone Insurance', type: 'organization' },
      { id: '2', name: 'Tech Solutions', type: 'organization' },
      { id: '3', name: 'Nurse Manager', type: 'role' },
      { id: '4', name: 'Senior Nurse', type: 'role' },
      { id: '5', name: 'Software Engineer', type: 'role' },
      { id: '6', name: 'Product Manager', type: 'role' },
      { id: '7', name: 'Data Scientist', type: 'role' },
      { id: '8', name: 'UX Designer', type: 'role' },
      { id: '9', name: 'DevOps Engineer', type: 'role' },
      { id: '10', name: 'Quality Assurance Analyst', type: 'role' },
    ],
    recentTasks: [
      { id: 't1', type: 'onboarding', status: 'completed', championName: 'Cameron Williams', userName: 'Hiro Jones', date: 'May 22' },
      { id: 't2', type: 'offboarding', status: 'completed', championName: 'Cameron Williams', userName: 'Dana Mills', date: 'May 22' },
      { id: 't3', type: 'offboarding', status: 'overdue', championName: 'Cameron Williams', userName: 'Dana Mills', date: 'Due May 20' },
    ],
    champions: [
      { id: 'c1', name: 'Cameron Williamson', email: 'cameron.williamson@example.com', role: 'primary' },
      { id: 'c2', name: 'Evelyn Hayes', email: 'evelyn.hayes@example.com', role: 'backup' },
    ],
    users: [
      { id: 'u1', name: 'Hiro Joyce', email: 'sophia.williams@innovatech.com', site: 'Monmouth Builders', jobTitle: 'Tax Officer', departments: ['Accounting', 'Managements'] },
      { id: 'u2', name: 'Liam Chen', email: 'liam.chen@techsolutions.com', site: 'Tech Solutions Inc.', jobTitle: 'Software Engineer', departments: ['Development', 'Innovation'] },
      { id: 'u3', name: 'Hiro Joyce', email: 'sophia.williams@innovatech.com', site: 'Monmouth Builders', jobTitle: 'Tax Officer', departments: ['Accounting', 'Managements'] },
      { id: 'u4', name: 'Emma Garcia', email: 'emma.garcia@creativestudio.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u5', name: 'Noah Smith', email: 'noah.smith@buildright.com', site: 'BuildRight Corp.', jobTitle: 'Project Manager', departments: ['Management', 'Construction'] },
      { id: 'u6', name: 'Olivia Brown', email: 'olivia.brown@marketingsolutions.com', site: 'Marketing Solutions', jobTitle: 'Marketing Specialist', departments: ['Marketing', 'Strategy'] },
      { id: 'u7', name: 'Elijah Wilson', email: 'elijah.wilson@financesmart.com', site: 'Finance Smart', jobTitle: 'Financial Analyst', departments: ['Finance', 'Analysis'] },
    ],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Bug tracking and agile project management',
    categories: ['Project Management', 'DevOps'],
    vendor: 'Atlassian Corporation Plc',
    logoColor: '#0052CC',
    logoInitials: 'JI',
    status: 'active',
    primaryChampion: 'Jenny Wilson',
    userCount: 28,
    lastSync: '10 minutes ago',
    provisioning: 'champion',
    appliesTo: [
      { id: '1', name: 'Riverstone Insurance', type: 'organization' },
      { id: '5', name: 'Software Engineer', type: 'role' },
    ],
    recentTasks: [
      { id: 't1', type: 'onboarding', status: 'completed', championName: 'Jenny Wilson', userName: 'Alex Park', date: 'May 20' },
    ],
    champions: [
      { id: 'c1', name: 'Jenny Wilson', email: 'jenny.wilson@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Alex Park', email: 'alex.park@example.com', site: 'HQ', jobTitle: 'Software Engineer', departments: ['Engineering'] },
    ],
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Project management and team collaboration',
    categories: ['Project Management', 'Collaboration'],
    vendor: 'Asana, Inc.',
    logoColor: '#F06A6A',
    logoInitials: 'AS',
    status: 'active',
    primaryChampion: 'Kristin Watson',
    userCount: 42,
    lastSync: '2 hours ago',
    provisioning: 'automatic',
    appliesTo: [
      { id: '6', name: 'Product Manager', type: 'role' },
    ],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Kristin Watson', email: 'kristin.watson@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Emma Garcia', email: 'emma.garcia@company.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u2', name: 'Noah Smith', email: 'noah.smith@company.com', site: 'BuildRight Corp.', jobTitle: 'Project Manager', departments: ['Management', 'Construction'] },
      { id: 'u3', name: 'James Lee', email: 'james.lee@company.com', site: 'HQ', jobTitle: 'Product Manager', departments: ['Product', 'Strategy'] },
      { id: 'u4', name: 'Olivia Brown', email: 'olivia.brown@company.com', site: 'Marketing Solutions', jobTitle: 'Marketing Specialist', departments: ['Marketing', 'Strategy'] },
      { id: 'u5', name: 'Benjamin Clark', email: 'benjamin.clark@company.com', site: 'BuildRight Corp.', jobTitle: 'Data Analyst', departments: ['Analytics', 'Data'] },
    ],
  },
  {
    id: 'basecamp',
    name: 'Basecamp',
    description: 'Project management and team communication hub',
    categories: ['Project Management', 'Communication'],
    vendor: 'Basecamp, LLC',
    logoColor: '#1D2D35',
    logoInitials: 'BC',
    status: 'active',
    primaryChampion: 'Annette Black',
    userCount: 15,
    lastSync: '1 hour ago',
    provisioning: 'champion',
    appliesTo: [
      { id: '3', name: 'Nurse Manager', type: 'role' },
    ],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Annette Black', email: 'annette.black@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Sophia Martinez', email: 'sophia.martinez@company.com', site: 'Monmouth Builders', jobTitle: 'Operations Manager', departments: ['Operations'] },
      { id: 'u2', name: 'Liam Chen', email: 'liam.chen@company.com', site: 'Tech Solutions Inc.', jobTitle: 'Software Engineer', departments: ['Development', 'Innovation'] },
      { id: 'u3', name: 'Mia Rodriguez', email: 'mia.rodriguez@company.com', site: 'Finance Smart', jobTitle: 'HR Manager', departments: ['HR', 'Administration'] },
      { id: 'u4', name: 'Lucas Anderson', email: 'lucas.anderson@company.com', site: 'HQ', jobTitle: 'Sales Representative', departments: ['Sales', 'Business Development'] },
    ],
  },
  {
    id: 'ms-teams',
    name: 'MS Teams',
    description: 'Team messaging and file sharing',
    categories: ['Communication', 'Collaboration'],
    isTopChoice: true,
    integration: {
      provisioning: 'SCIM (Automatic)',
      authentication: 'SSO Supported',
      setupTime: '10 minutes',
      planRequired: 'Standard',
    },
    howItWorks: [
      {
        type: 'scim',
        label: 'SCIM Enabled',
        description: 'This app supports automatic user provisioning through SCIM (System for Cross-domain Identity Management). When enabled, new employees will automatically receive access, and departing employees will be automatically deprovisioned.',
      },
      {
        type: 'champion',
        label: 'Champion Method',
        description: 'For apps without API integration, your designated Champion will receive notifications to manually provision access. This ensures all apps can be managed through CubX, even those without automation.',
      },
    ],
    vendor: 'Microsoft Corporation',
    logoColor: '#4B53BC',
    logoInitials: 'MT',
    status: 'active',
    primaryChampion: 'Cameron Williamson',
    userCount: 47,
    lastSync: '3 minutes ago',
    provisioning: 'champion',
    appliesTo: [
      { id: '1', name: 'Riverstone Insurance', type: 'organization' },
    ],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Cameron Williamson', email: 'cameron.williamson@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Emma Garcia', email: 'emma.garcia@company.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u2', name: 'Liam Chen', email: 'liam.chen@company.com', site: 'Tech Solutions Inc.', jobTitle: 'Software Engineer', departments: ['Development', 'Innovation'] },
      { id: 'u3', name: 'Noah Smith', email: 'noah.smith@company.com', site: 'BuildRight Corp.', jobTitle: 'Project Manager', departments: ['Management', 'Construction'] },
      { id: 'u4', name: 'Ava Johnson', email: 'ava.johnson@company.com', site: 'HQ', jobTitle: 'UX Designer', departments: ['Design', 'Product'] },
      { id: 'u5', name: 'William Davis', email: 'william.davis@company.com', site: 'Tech Solutions Inc.', jobTitle: 'DevOps Engineer', departments: ['Engineering', 'Infrastructure'] },
      { id: 'u6', name: 'Sophia Martinez', email: 'sophia.martinez@company.com', site: 'Monmouth Builders', jobTitle: 'Operations Manager', departments: ['Operations'] },
    ],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'All-in-one workspace for notes and documentation',
    categories: ['Productivity', 'Collaboration'],
    vendor: 'Notion Labs Inc.',
    logoColor: '#000000',
    logoInitials: 'NO',
    status: 'active',
    primaryChampion: 'Jane Cooper',
    userCount: 19,
    lastSync: '15 minutes ago',
    provisioning: 'automatic',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Jane Cooper', email: 'jane.cooper@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'James Lee', email: 'james.lee@company.com', site: 'HQ', jobTitle: 'Product Manager', departments: ['Product', 'Strategy'] },
      { id: 'u2', name: 'Isabella Thompson', email: 'isabella.thompson@company.com', site: 'Creative Studio', jobTitle: 'Content Writer', departments: ['Marketing', 'Creative'] },
      { id: 'u3', name: 'Elijah Wilson', email: 'elijah.wilson@company.com', site: 'Finance Smart', jobTitle: 'Financial Analyst', departments: ['Finance', 'Analysis'] },
      { id: 'u4', name: 'Olivia Brown', email: 'olivia.brown@company.com', site: 'Marketing Solutions', jobTitle: 'Marketing Specialist', departments: ['Marketing', 'Strategy'] },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Team communication and collaboration platform',
    categories: ['Communication', 'Collaboration'],
    isTopChoice: true,
    integration: {
      provisioning: 'SCIM (Automatic)',
      authentication: 'SSO Supported',
      setupTime: '10 minutes',
      planRequired: 'Standard',
    },
    howItWorks: [
      {
        type: 'scim',
        label: 'SCIM Enabled',
        description: 'This app supports automatic user provisioning through SCIM (System for Cross-domain Identity Management). When enabled, new employees will automatically receive access, and departing employees will be automatically deprovisioned.',
      },
      {
        type: 'champion',
        label: 'Champion Method',
        description: 'For apps without API integration, your designated Champion will receive notifications to manually provision access. This ensures all apps can be managed through CubX, even those without automation.',
      },
    ],
    overviewText: 'Slack is a cloud-based team communication platform that brings all your communication together in one place. It offers real-time messaging, file sharing, and powerful search that makes it easy for teams to stay aligned and work together more effectively. With channels organized by project, topic, or team, Slack helps reduce email clutter and keeps conversations focused and accessible.\n\nSlack integrates with hundreds of tools your team already uses — from Google Drive and Zoom to Jira and Salesforce — so you can work without constantly switching between apps. Automated workflows and reminders help you stay on top of action items, while threaded conversations keep discussions organized and easy to follow up on.\n\nYour IT team manages Slack access on your behalf. Channels are provisioned based on your department and role, and you\'ll be added to relevant workspaces automatically when you join. If you need access to a specific channel or workspace, reach out to your App Manager above.',
    appUrl: '#',
    supportUrl: '#',
    pricing: 'Freemium',
    builtBy: 'Slack',
    resources: [
      { label: 'Company website', url: '#' },
      { label: 'Documentation', url: '#' },
      { label: 'FAQ', url: '#' },
    ],
    vendor: 'Salesforce.com, Inc.',
    logoColor: '#4A154B',
    logoInitials: 'SL',
    status: 'active',
    primaryChampion: 'Courtney Henry',
    userCount: 50,
    lastSync: '5 minutes ago',
    provisioning: 'champion',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Courtney Henry', email: 'courtney.henry@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Emma Garcia', email: 'emma.garcia@company.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u2', name: 'Liam Chen', email: 'liam.chen@company.com', site: 'Tech Solutions Inc.', jobTitle: 'Software Engineer', departments: ['Development', 'Innovation'] },
      { id: 'u3', name: 'Noah Smith', email: 'noah.smith@company.com', site: 'BuildRight Corp.', jobTitle: 'Project Manager', departments: ['Management', 'Construction'] },
      { id: 'u4', name: 'Olivia Brown', email: 'olivia.brown@company.com', site: 'Marketing Solutions', jobTitle: 'Marketing Specialist', departments: ['Marketing', 'Strategy'] },
      { id: 'u5', name: 'James Lee', email: 'james.lee@company.com', site: 'HQ', jobTitle: 'Product Manager', departments: ['Product', 'Strategy'] },
      { id: 'u6', name: 'Isabella Thompson', email: 'isabella.thompson@company.com', site: 'Creative Studio', jobTitle: 'Content Writer', departments: ['Marketing', 'Creative'] },
    ],
  },
  {
    id: 'slack-2',
    name: 'Slack',
    description: 'Team communication and collaboration platform',
    categories: ['Communication', 'Collaboration'],
    vendor: 'Salesforce.com, Inc.',
    logoColor: '#4A154B',
    logoInitials: 'SL',
    status: 'configuring',
    primaryChampion: 'Devon Lane',
    userCount: 50,
    lastSync: '20 minutes ago',
    provisioning: 'champion',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Devon Lane', email: 'devon.lane@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Benjamin Clark', email: 'benjamin.clark@company.com', site: 'BuildRight Corp.', jobTitle: 'Data Analyst', departments: ['Analytics', 'Data'] },
      { id: 'u2', name: 'Mia Rodriguez', email: 'mia.rodriguez@company.com', site: 'Finance Smart', jobTitle: 'HR Manager', departments: ['HR', 'Administration'] },
      { id: 'u3', name: 'Lucas Anderson', email: 'lucas.anderson@company.com', site: 'HQ', jobTitle: 'Sales Representative', departments: ['Sales', 'Business Development'] },
    ],
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    description: 'All-in-one productivity and project management',
    categories: ['Project Management', 'Productivity'],
    vendor: 'Mango Technologies, Inc.',
    logoColor: '#7B68EE',
    logoInitials: 'CU',
    status: 'configuring',
    primaryChampion: 'Floyd Miles',
    userCount: 30,
    lastSync: '1 hour ago',
    provisioning: 'champion',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Floyd Miles', email: 'floyd.miles@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Ava Johnson', email: 'ava.johnson@company.com', site: 'HQ', jobTitle: 'UX Designer', departments: ['Design', 'Product'] },
      { id: 'u2', name: 'William Davis', email: 'william.davis@company.com', site: 'Tech Solutions Inc.', jobTitle: 'DevOps Engineer', departments: ['Engineering', 'Infrastructure'] },
      { id: 'u3', name: 'Sophia Martinez', email: 'sophia.martinez@company.com', site: 'Monmouth Builders', jobTitle: 'Operations Manager', departments: ['Operations'] },
    ],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'CRM, marketing and sales automation platform',
    categories: ['CRM & Sales', 'Marketing'],
    vendor: 'HubSpot, Inc.',
    logoColor: '#FF7A59',
    logoInitials: 'HS',
    status: 'active',
    primaryChampion: 'Brooklyn Simmons',
    userCount: 15,
    lastSync: '8 minutes ago',
    provisioning: 'automatic',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Brooklyn Simmons', email: 'brooklyn.simmons@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Lucas Anderson', email: 'lucas.anderson@company.com', site: 'HQ', jobTitle: 'Sales Representative', departments: ['Sales', 'Business Development'] },
      { id: 'u2', name: 'Olivia Brown', email: 'olivia.brown@company.com', site: 'Marketing Solutions', jobTitle: 'Marketing Specialist', departments: ['Marketing', 'Strategy'] },
      { id: 'u3', name: 'Isabella Thompson', email: 'isabella.thompson@company.com', site: 'Creative Studio', jobTitle: 'Content Writer', departments: ['Marketing', 'Creative'] },
      { id: 'u4', name: 'Elijah Wilson', email: 'elijah.wilson@company.com', site: 'Finance Smart', jobTitle: 'Financial Analyst', departments: ['Finance', 'Analysis'] },
      { id: 'u5', name: 'Mia Rodriguez', email: 'mia.rodriguez@company.com', site: 'Finance Smart', jobTitle: 'HR Manager', departments: ['HR', 'Administration'] },
    ],
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Collaborative design and prototyping tool',
    categories: ['Design & Creative'],
    isTopChoice: true,
    integration: {
      provisioning: 'Champion Method',
      authentication: 'SSO Supported',
      setupTime: '15 minutes',
      planRequired: 'Professional',
    },
    howItWorks: [
      {
        type: 'champion',
        label: 'Champion Method',
        description: 'For apps without API integration, your designated Champion will receive notifications to manually provision access. This ensures all apps can be managed through CubX, even those without automation.',
      },
    ],
    vendor: 'Microsoft Corporation',
    logoColor: '#F24E1E',
    logoInitials: 'FI',
    status: 'active',
    primaryChampion: 'Brecket Roberta',
    userCount: 66,
    lastSync: '12 minutes ago',
    provisioning: 'champion',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Brecket Roberta', email: 'brecket.roberta@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Emma Garcia', email: 'emma.garcia@company.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u2', name: 'Ava Johnson', email: 'ava.johnson@company.com', site: 'HQ', jobTitle: 'UX Designer', departments: ['Design', 'Product'] },
      { id: 'u3', name: 'Isabella Thompson', email: 'isabella.thompson@company.com', site: 'Creative Studio', jobTitle: 'Content Writer', departments: ['Marketing', 'Creative'] },
      { id: 'u4', name: 'James Lee', email: 'james.lee@company.com', site: 'HQ', jobTitle: 'Product Manager', departments: ['Product', 'Strategy'] },
      { id: 'u5', name: 'Noah Smith', email: 'noah.smith@company.com', site: 'BuildRight Corp.', jobTitle: 'Project Manager', departments: ['Management', 'Construction'] },
      { id: 'u6', name: 'Sophia Martinez', email: 'sophia.martinez@company.com', site: 'Monmouth Builders', jobTitle: 'Operations Manager', departments: ['Operations'] },
    ],
  },
  {
    id: 'miro',
    name: 'Miro',
    description: 'Online collaborative whiteboard platform',
    categories: ['Design & Creative', 'Collaboration'],
    vendor: 'Microsoft Corporation Plc.',
    logoColor: '#FFD02F',
    logoInitials: 'MI',
    status: 'active',
    primaryChampion: 'Floyd Miles',
    userCount: 288,
    lastSync: '30 minutes ago',
    provisioning: 'automatic',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Floyd Miles', email: 'floyd.miles@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Ava Johnson', email: 'ava.johnson@company.com', site: 'HQ', jobTitle: 'UX Designer', departments: ['Design', 'Product'] },
      { id: 'u2', name: 'Emma Garcia', email: 'emma.garcia@company.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u3', name: 'Liam Chen', email: 'liam.chen@company.com', site: 'Tech Solutions Inc.', jobTitle: 'Software Engineer', departments: ['Development', 'Innovation'] },
      { id: 'u4', name: 'Benjamin Clark', email: 'benjamin.clark@company.com', site: 'BuildRight Corp.', jobTitle: 'Data Analyst', departments: ['Analytics', 'Data'] },
      { id: 'u5', name: 'Isabella Thompson', email: 'isabella.thompson@company.com', site: 'Creative Studio', jobTitle: 'Content Writer', departments: ['Marketing', 'Creative'] },
    ],
  },
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'Work operating system for teams and projects',
    categories: ['Project Management', 'Collaboration'],
    vendor: 'Monday.com Ltd.',
    logoColor: '#F62B54',
    logoInitials: 'MO',
    status: 'active',
    primaryChampion: 'Cameron Williamson',
    userCount: 47,
    lastSync: '7 minutes ago',
    provisioning: 'champion',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Cameron Williamson', email: 'cameron.williamson@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Noah Smith', email: 'noah.smith@company.com', site: 'BuildRight Corp.', jobTitle: 'Project Manager', departments: ['Management', 'Construction'] },
      { id: 'u2', name: 'James Lee', email: 'james.lee@company.com', site: 'HQ', jobTitle: 'Product Manager', departments: ['Product', 'Strategy'] },
      { id: 'u3', name: 'Sophia Martinez', email: 'sophia.martinez@company.com', site: 'Monmouth Builders', jobTitle: 'Operations Manager', departments: ['Operations'] },
      { id: 'u4', name: 'Olivia Brown', email: 'olivia.brown@company.com', site: 'Marketing Solutions', jobTitle: 'Marketing Specialist', departments: ['Marketing', 'Strategy'] },
      { id: 'u5', name: 'Mia Rodriguez', email: 'mia.rodriguez@company.com', site: 'Finance Smart', jobTitle: 'HR Manager', departments: ['HR', 'Administration'] },
    ],
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    description: 'Productivity and collaboration suite by Google',
    categories: ['Productivity', 'Collaboration'],
    vendor: 'Google LLC',
    logoColor: '#4285F4',
    logoInitials: 'GW',
    status: 'active',
    primaryChampion: 'Cody Fisher',
    userCount: 65,
    lastSync: '4 minutes ago',
    provisioning: 'saml',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Cody Fisher', email: 'cody.fisher@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Liam Chen', email: 'liam.chen@company.com', site: 'Tech Solutions Inc.', jobTitle: 'Software Engineer', departments: ['Development', 'Innovation'] },
      { id: 'u2', name: 'William Davis', email: 'william.davis@company.com', site: 'Tech Solutions Inc.', jobTitle: 'DevOps Engineer', departments: ['Engineering', 'Infrastructure'] },
      { id: 'u3', name: 'Emma Garcia', email: 'emma.garcia@company.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u4', name: 'Elijah Wilson', email: 'elijah.wilson@company.com', site: 'Finance Smart', jobTitle: 'Financial Analyst', departments: ['Finance', 'Analysis'] },
      { id: 'u5', name: 'Isabella Thompson', email: 'isabella.thompson@company.com', site: 'Creative Studio', jobTitle: 'Content Writer', departments: ['Marketing', 'Creative'] },
      { id: 'u6', name: 'Lucas Anderson', email: 'lucas.anderson@company.com', site: 'HQ', jobTitle: 'Sales Representative', departments: ['Sales', 'Business Development'] },
    ],
  },
  {
    id: 'docusign',
    name: 'DocuSign',
    description: 'Electronic signature and agreement cloud platform',
    categories: ['E-Signature', 'Document Management'],
    vendor: 'DocuSign Inc.',
    logoColor: '#4C00FF',
    logoInitials: 'DS',
    status: 'configuring',
    primaryChampion: 'Leslie Alexander',
    userCount: 11,
    lastSync: '2 hours ago',
    provisioning: 'champion',
    appliesTo: [],
    recentTasks: [],
    champions: [
      { id: 'c1', name: 'Leslie Alexander', email: 'leslie.alexander@example.com', role: 'primary' },
    ],
    users: [
      { id: 'u1', name: 'Emma Garcia', email: 'emma.garcia@company.com', site: 'Creative Studio', jobTitle: 'Graphic Designer', departments: ['Design', 'Branding'] },
      { id: 'u2', name: 'Lucas Anderson', email: 'lucas.anderson@company.com', site: 'HQ', jobTitle: 'Sales Representative', departments: ['Sales', 'Business Development'] },
      { id: 'u3', name: 'Mia Rodriguez', email: 'mia.rodriguez@company.com', site: 'Finance Smart', jobTitle: 'HR Manager', departments: ['HR', 'Administration'] },
    ],
  },
]
